baseURL = 'http://asterlinux.github.io/'
languageCode = 'en-us'
title = 'Aster Linux'
SectionPagesMenu = "main"
Paginate = 12
theme = 'ananke'
enableRobotsTXT = true

[sitemap]
  changefreq = "weekely"
  priority = 0.8
  filename = "sitemap.xml"


[params]
  site_logo = "img/asterlinux-small.png"
  favicon = "img/asterlinux.svg"
  background_color_class = "bg-mid-gray"
  body_classes = "bg-silver"
  DisqusShortname = "asterlinux-github-io"
  text_color = "black"
  description = "Arch Linux Based Distribution"
  author = "Sahan Rasanjana"


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/sahan_user"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/asterlinux"


